@startuml
ditaa

              +---------------------------------------------------------------------------------------------------------------------------+
              |                                                                                                                           |
              |                                                          logtee                                                           |
              |                                                                                                                           |
              |                                                                                                                    +------+--------------+
              |                                                                                                                    |                     |
              |                                                    +-------------------------------------------------------------->|                     |
              |                                                    |                                                               |            stdout   |
              |                                                    |                                                               |                     |
              |                                                    |                                                               |                cGRE |
              |                                                    |                                                               +------+--------------+
              |                   +---------------------------+    |                 +---------------------------+                        |
              |                   |                           |    |                 |                           |                        |
              |                   |           child           |    |                 |         forwarder         |                        |
              |                   |                      +----+----+--+              |                      +----+-----=-+                |
              |                   |                      |            |              |                      |            |                |
+-------------+-------+           |                      |     stdout |              |                      |     stdout  X               |
|                     |   +-------+----+                 |       cGRE |              |                      |       cGRE |                |
|                     |   |            |                 +----+----+--+      +-------+----+                 +----+-----=-+                |
|  stdin              +-->| stdin      |                      |    |         |            |                      |                        |
|                     |   |       cBLU |                      |    +-------->| stdin      |                      |                        |
|                cBLU |   +-------+----+                      |              |       cBLU |                      |                        |
+-------------+-------+           |                           |              +-------+----+                      |                        |
              |                   |                      +----+-------+              |                      +----+-------+                |
              |                   |                      |            |              |                      |            |                |
              |                   |                      |     stderr |              |                      |     stderr |                |
              |                   |                      |       cRED |              |                      |       cRED |         +------+--------------+
              |                   |                      +----+----+--+              |                      +----+----+--+         |                     |
              |                   |                      c888 |    |                 |                      c888 |    |            |                     |
              |                   +---------------------------+    |                 +---------------------------+    +----------->|            stderr   |
              |                                                    |                                                               |                     |
              |                                                    +-------------------------------------------------------------->|                cRED |
              |                                                                                                                    +------+--------------+
              |                                                                                                                     cFFF  |
              +---------------------------------------------------------------------------------------------------------------------------+

@enduml