@startuml

() "stdin" as stdin_logtee
stdin_logtee -right- Logtee
() "stdout" as stdout_logtee
stdout_logtee -left- Logtee
() "stderr" as stderr_logtee
stderr_logtee -up- Logtee

component Logtee {
    () "stdin" as stdin_child
    stdin_child -right- child
    () "stdout" as stdout_child
    stdout_child -left- child
    () "stderr" as stderr_child
    stderr_child -up- child

    () "stdin" as stdin_forwarder
    stdin_forwarder -right- forwarder
    () "stdout" as stdout_forwarder
    stdout_forwarder -left- forwarder
    () "stderr" as stderr_forwarder
    stderr_forwarder -up- forwarder

    stdin_logtee -> stdin_child
    stdout_child -> stdout_logtee
    stdout_child -> stdin_forwarder
    stderr_child -> stderr_logtee
    stderr_forwarder -> stderr_logtee

    component "child" {
    }

    component "forwarder" {
    }

}
@enduml